language: php
php:
  - '7.2'
  - '7.3'

before_script:
  - phpenv config-rm xdebug.ini
  - git fetch --unshallow
  - mkdir -p build/logs

install:
  - composer install --no-interaction

script:
  - composer run-script lint
  - composer run-script test

after_success:
  - travis_retry php vendor/bin/php-coveralls

notifications:
  email: false
